name: drawer
version: '${version}'

main: fr.hadrix.drawer.Drawer
api-version: '1.21'
commands:

  drawer:
    description: Drawer Plugin Command
    usage: /<command> [give|list]
    permission : drawer.use
    default: true

